//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace credit_normal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_data
    {
        public int ID { get; set; }
        public string Last_name { get; set; }
        public string First_name { get; set; }
        public string Father_name { get; set; }
        public bool Sex { get; set; }
        public long Passport { get; set; }
        public Nullable<long> INN { get; set; }
        public string Adress { get; set; }
        public string Real_adress { get; set; }
        public bool Marriage { get; set; }
        public string Job { get; set; }
        public string Job_position { get; set; }
        public Nullable<double> salary { get; set; }
        public double Credit_score { get; set; }
        public int report { get; set; }
    
        public virtual Rep Rep { get; set; }
    }
}
