//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace credit_normal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rep()
        {
            this.Client_data = new HashSet<Client_data>();
        }
    
        public int ID { get; set; }
        public bool INN { get; set; }
        public int Tax_debits { get; set; }
        public int FSSP { get; set; }
        public int Bankruptcy { get; set; }
        public bool Wanted { get; set; }
    
        public virtual Bankrupcy Bankrupcy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_data> Client_data { get; set; }
        public virtual FSSP FSSP1 { get; set; }
        public virtual Tax_debit Tax_debit { get; set; }
    }
}
